### ISSUE TITLE
Printing Polar Coords with values between -1 and 0 as DMS strings gives negative values

### ISSUE THREAD

**Issue by OHalford-Novetta** [the42/cartconvert#3]
I have a list of lat/ lon coordinates in degrees that I wanted to print out in dms format using `LatLongToString`, and any with values between -1 and 0 have negative minute and second values. The direction, however, is exactly what it should be. 

Input:                  {"Lat":-79.67361389481076,"Lon":-0.02303728307597319}
Expected Result: {"DMSLat":"S 79°40'25.01''","DMSLon":"W 0°1'22.93''"}
Output:               {"DMSLat":"S 79°40'25.01''","DMSLon":"W 0°-1'-22.93''"}

**Comment by the42** [comment]
Fixed with #233561ac  thanks for reporting!
